import './globals.css'
import type { Metadata } from 'next'
import { Inter  } from 'next/font/google'
const nunito = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Infinite Scroll',
  description: 'Generated by Bahar',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
           {children}
      </body>
    </html>
  )
}
